### PR TITLE
differentiate using question based on existence of God

### PR DESCRIPTION
**Pull request by vishaltelangre**
I think we can differentiate population by asking this simple question about their beliefs regarding existence of God. I have  experienced very less amount of people in my life who are agnostic, BTW.

### CODE REVIEW

**Comment by BarbaricCorgi** [comment]
You mean religious affiliation or atheism/non-atheism?

**Comment by vishaltelangre** [comment]
@sdreyesg: Oh, I meant people who think that there is something and it exist, they have faith in. And the people who don't think like that. Is this the answer to your question?

**Comment by BarbaricCorgi** [comment]
@vishaltelangre yes, it answered my question. thank you. This question is not closer to the desired distribution of 50/50 between the person answering the test. let me explain, according to http://en.wikipedia.org/wiki/Religion_demographics around 16% of world population are not affiliated to any religious group.

regards.

**Comment by vishaltelangre** [comment]
@sdreyesg: How do you relate it with the OP's description:

<blockquote>
What if, instead assigning 1s and 0s, we had 33 'Yes' or 'No' general questions that, when answered correctly, uniquely identified everyone on the planet.
</blockquote>
 

I didn't get it. I see people does believe in the existence of something they have faith in, and other kind people which doesn't believe it. That's a 50-50 distribution approximately. And that's a quite useful measurement to differentiate people, and could help to determine their mentalities, views and other sort of behaviors in regard with different things and incidences.

**Comment by BarbaricCorgi** [comment]
Search for religion demographics in wikipedia. Agnostic people represent an
amount considerable of people, but is around 16/84, not 50/50

**Pull request closed without merging**
