### PR TITLE
Do you believe in GOD?

### PR DESCRIPTION
**Pull request by tarunasharma89**

### CODE REVIEW

**Comment by amandasaurus** [comment]
You'd have to define _what_ god. Or someone might think "The questioner is European, so they probably mean Jesus, and I don't believe in that, so I'll answer "No"".

Additionally, some people believe in 2 or many gods, not just "one god".

**Comment by MarkDunne** [comment]
I guess you could group a couple of beliefs such as certain gods or non belief together to form a 50/50 split. But in it's current form, this question will not work

**Comment by tarunasharma89** [comment]
GOD can be anything! In India ,some people consider gurus/preachers of gods as GODs. In this question, I meant if you believe in some super natural thing who u think has created the universe, something that you worship so that some miracles can happen in your life?

**Comment by jmurth1234** [comment]
How about "Do you believe in a deity or multiple deities?"

**Comment by tarunasharma89** [comment]
Some people are atheist so this question wont cover them up!

**Comment by ayberk** [comment]
I think it would be better to ask "Do you believe in an omnipotent force or being?"

**Comment by jmurth1234** [comment]
Not everyone who believes in a deity believes that they are omnipotent

—

**Pull request closed without merging**
