### PR TITLE
Are you the firstborn child?

### PR DESCRIPTION
**Pull request by gtanczyk**
That's very easy to answer yet it affects entire population.

### CODE REVIEW

**Comment by amandasaurus** [comment]
For who? Your mother or father?

**Comment by gtanczyk** [comment]
Good question!

Father will say: you are my firstborn, same can be said by mother, yet it's not exclusive.

So as along as you are firstborn for any of your parents, you are a firstborn.

"Are you the oldest of siblings?" could be an other question.

**Comment by aaronleesmith** [comment]
Does this divide the population relatively evenly? Statistically, are there as many firstborns as non-firstborns? It would seem that second...n born children would skew this set.

**Comment by edsrzf** [comment]
My guess is that this question doesn't divide the population in half.

There's some data for average number of children per person in the United States available [here](http://blogs.discovermagazine.com/gnxp/2012/08/what-is-the-distribution-of-offspring-per-individual). Based on this data, roughly 1/3 of people would answer "yes" to this question and the other 2/3 would answer "no". It's doubtful that the distributions in the rest of the world are different enough to balance things out. China would probably help, though, with their one child policy.

I also think only the father or mother's side should be considered. I've chosen the mother, but I don't think there's any reason to prefer one over the other.

I'd consider asking something like "Do you have more maternal siblings who are younger than you than maternal siblings who are older than you?"

If all children were born in pairs, this question would divide the population perfectly in half. The problem is how to evenly divide middle children, including only children.

Based on the data above, we might get close by adding "or are you the second of three children?" I think we need more data to know for sure, though.

**Comment by gtanczyk** [comment]
We need at least two questions to make unique characteristic for siblings anyway.

**Comment by edsrzf** [comment]
Why? And even if that's true, all questions still need to come close to splitting the population in half.

**Comment by aaronleesmith** [comment]
Yeah, I don't think the issue here is the characterization of questions but the balance of this question not providing a somewhat evenly distributed binary result.

**Comment by gtanczyk** [comment]
I can imagine situations, when characteristic such as being the first born child would be the only one, which could let us make a distinction between two persons. Twins are primary example, but not only, it depends on other questions.

**Pull request closed without merging**
