### PR TITLE
Do you have access to the internet?

### PR DESCRIPTION
**Pull request by marvinbarretto**
Do you have access to the internet?

According to p.10 of this report cited below, at the moment about 50% of the world is currently connected.

This question essentially splits poor and rich people which is arguably happening somewhat already in question #2 though..?

http://www.itu.int/en/ITU-D/Statistics/Documents/publications/mis2012/MIS2012_without_Annex_4.pdf

### CODE REVIEW

**Comment by BarbaricCorgi** [comment]
Good one

**Comment by ghandhikus** [comment]
Actually nearly everybody who is going to do this test have internet. The question should split people between others.

**Comment by darioml** [comment]
1 - Questions shouldn't be based on highly volatile figures. Consider that perhaps 5-10 years from now, many more people will have a connection
2 - http://en.wikipedia.org/wiki/Global_Internet_usage 39% is not splitting the population in half
3 - This is not independent form Q2..

**Comment by BarbaricCorgi** [comment]
@darioml we should accept volatility. answering this test should give you the most possible approximation to your identity, nonetheless, your identity actually change in time.

e.g.
You moved from your country
You get older
People die and born
People even change its gender

So volatility is solved by considering that when you answer this test you will get an approximation with the data you supply in a moment in time. the opposite direction will be assign a country ID and a citizen ID, for example, it will require a greater amount of bits, but is resilient to the volatility of our own identity.

**Pull request closed without merging**
