### PR TITLE
Added a religion question based in world demographics

### PR DESCRIPTION
**Pull request by BarbaricCorgi**

### CODE REVIEW

**Comment by aaronleesmith** [comment]
This is the same as #60 and #40

**Comment by BarbaricCorgi** [comment]
Crap, you're right. Hadn't seen them before

**Comment by JoshuaGross** [comment]
@ajmalk It's the world distribution, not per-country. For example, "Ancient Abrahamic Religions" (Judaism, Christianity, Islam) vs. all others would split the world roughly in half (roughly 55/45%): http://en.wikipedia.org/wiki/Major_religious_groups

**Comment by ajmalk** [comment]
> As an example, having both the questions "Are you male?" and "Are you below the median age?" will not work because there are more females above the median age than men. Separately they might divide the population, but together they will not split the population into 4 group of 25% as required.

From the description page. So no this won't work. Every question will have to split every bucket in half. At least that's how I understand it.

**Comment by JoshuaGross** [comment]
@ajmalk  I spoke too soon, thanks for clarifying. Makes sense.

**Pull request closed without merging**
